### ISSUE TITLE
Dataloader question

### ISSUE THREAD

**Issue by timrs2998** [gramps-graphql/gramps-express#47]
Looking at the [GraphQLConnector](https://github.com/gramps-graphql/gramps-express/blob/master/src/helpers/GraphQLConnector.js#L167), the dataloader is constructed every time `get()` is called. This means every HTTP call creates a new dataloader, rather than getting a new dataloader for every graphql request.

It looks like the models and connectors are singletons constructed once, and not for every request. Looking at the [GitHunt api](https://github.com/apollographql/GitHunt-API/blob/master/api/server.js#L143), a new model and connector are created for every single request. I'm thinking gramps' behavior should change to match the GitHunt API to enable using dataloaders correctly.

Should the behavior be changed to construct the datasources for each request, rather than treating them as singletons? Otherwise I'm uncertain how per-request caching can occur using dataloaders.

**Comment by jlengstorf** [comment]
This is a great question, and one that I'd need a use case to understand better. Is the concern that the dataloader would respond with stale data? Or something else?

We haven't seen any issues with this in production, but I'd be really interested to hear more about what the potential issue is.

**Comment by timrs2998** [comment]
@jlengstorf I tried to demonstrate the issue in https://github.com/gramps-graphql/data-source-base/pull/3 , let me know if that makes sense

**Comment by timrs2998** [comment]
I think what I'm looking for is to define datasources as functions, ie:

```es6
export default (req, res) => ({
  context: 'CoreItem',
  model: new Model({ connector: new Connector() }),
  schema,
  resolvers,
});
```

So dataloaders can be used in the connectors to prevent duplicate requests and for batching requests. Without some fix, I don't see an easy way to get any of the benefits of using dataloaders.

**Comment by jlengstorf** [comment]
Hey, @timrs2998 — I've been on vacation, so thanks for your patience.

I think you're right, and I need to pull down your PR and make sure we're caching requests per-request as dataloader is designed to do, but never serving stale data (which is how we got to creating a new dataloader on each call to `get`). But I do believe you're right that the connector needs to be created for each _request_, and not a new dataloader for each method call.

I most likely won't be able to dig into this until next week. If you've got a working test case that shows we're getting the correct results and dataloader behavior, that would be really helpful.

Thanks!

**Comment by timrs2998** [comment]
I tried to demonstrate the issue in the PR https://github.com/gramps-graphql/data-source-base/pull/3 although I'm lacking a test case. I'll try and work on submitting a test case in the Jest test suite probably Friday.

Take your time and enjoy your vacation.

**Comment by Maxhodges** [comment]
what about adding a cache layer below graphql so it can look into redis or memcached cache before falling through to a more expensive database query?
